const Sequelize = require('sequelize')
const dblabdados = require('../config/labdados')
const dbportalrelatorio = require('../config/portalrelatorio')

const Relatorios = require('../models/Relatorio')
const Proposta = require('../models/Proposta')
const Clientes = require('../models/Clientes')
const Emails = require('../models/PortalEmails')
const Downloads = require('../models/PortalDownload')
const Setores = require('../models/Setores')
const PortalRelatorio = require('../models/PortalRelatorio')
const Users = require('../models/UsersPermission')
const Group = require('../models/Group')
const GroupEmail = require('../models/GroupEmail')
const Login = require('../models/Login')
const EmailsCopia = require('../models/EmailsCopia')
const PortalEmailsEnviados = require('../models/PortalEmailsEnviados')
const Observation = require('../models/Observation')
const Log = require('../models/Log')

const connectionlabdados = new Sequelize(dblabdados)
const connectionportalrelatorio = new Sequelize(dbportalrelatorio)

Relatorios.init(connectionportalrelatorio)
Users.init(connectionportalrelatorio)
Emails.init(connectionportalrelatorio)
Downloads.init(connectionportalrelatorio)
PortalRelatorio.init(connectionportalrelatorio)
Group.init(connectionportalrelatorio)
GroupEmail.init(connectionportalrelatorio)
Login.init(connectionportalrelatorio)
EmailsCopia.init(connectionportalrelatorio)
PortalEmailsEnviados.init(connectionportalrelatorio)
Observation.init(connectionportalrelatorio)
Log.init(connectionportalrelatorio)

Proposta.init(connectionlabdados)
Clientes.init(connectionlabdados)
Setores.init(connectionlabdados)

module.exports = { connectionlabdados, connectionportalrelatorio }
